
development:
  adapter: postgresql
  encoding: unicode
  database: energyai_development
  username: 
  password:
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: energyai_development
  #database: energyai_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: energyai_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test