
development:
  #adapter: postgresql
  adapter: mysql
  #encoding: unicode
  encoding: utf8
  database: energyai_development
  username: 
  password:
  host: localhost
  pool: 5

test: &test
  #adapter: postgresql
  adapter: mysql
  #encoding: unicode
  encoding: utf8
  database: energyai_test
  pool: 5
  username: 
  password:

production:
  #adapter: postgresql
  adapter: mysql
  #encoding: unicode
  encoding: utf8
  database: energyai_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test